# Generated by Django 4.0.5 on 2022-06-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slidename', models.CharField(max_length=50, verbose_name='slidename')),
                ('slideabout', models.TextField(verbose_name='slideabout')),
                ('slideimg', models.ImageField(upload_to='media', verbose_name='slideimage')),
                ('itemname', models.CharField(max_length=50, verbose_name='itemname')),
                ('itemabout', models.TextField(verbose_name='itemabout')),
                ('itemimg', models.ImageField(upload_to='media', verbose_name='itemimage')),
            ],
        ),
    ]
