# Generated by Django 4.0.5 on 2022-06-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_home'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name': 'Home', 'verbose_name_plural': 'Homs'},
        ),
        migrations.AlterField(
            model_name='home',
            name='itemabout',
            field=models.TextField(blank=True, verbose_name='itemabout'),
        ),
        migrations.AlterField(
            model_name='home',
            name='itemimg',
            field=models.ImageField(blank=True, upload_to='media', verbose_name='itemimage'),
        ),
        migrations.AlterField(
            model_name='home',
            name='itemname',
            field=models.CharField(blank=True, max_length=50, verbose_name='itemname'),
        ),
        migrations.AlterField(
            model_name='home',
            name='slideabout',
            field=models.TextField(blank=True, verbose_name='slideabout'),
        ),
        migrations.AlterField(
            model_name='home',
            name='slideimg',
            field=models.ImageField(blank=True, upload_to='media', verbose_name='slideimage'),
        ),
        migrations.AlterField(
            model_name='home',
            name='slidename',
            field=models.CharField(blank=True, max_length=50, verbose_name='slidename'),
        ),
    ]
