# Generated by Django 4.0.5 on 2022-06-11 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_home_options_alter_home_itemabout_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Product name')),
                ('about', models.TextField(verbose_name='Product about')),
                ('price', models.IntegerField(verbose_name='Product price')),
                ('img', models.ImageField(upload_to='media', verbose_name='Product image')),
            ],
            options={
                'verbose_name': 'HomeProduct',
                'verbose_name_plural': 'HomeProducts',
            },
        ),
        migrations.CreateModel(
            name='HomeSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Slide name')),
                ('about', models.TextField(verbose_name='Slide about')),
                ('img', models.ImageField(upload_to='media', verbose_name='Smilde image')),
            ],
            options={
                'verbose_name': 'HomeSlide',
                'verbose_name_plural': 'HomeSlides',
            },
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Home',
        ),
    ]
